name: EVCA-gpu
channels:
  - conda-forge
dependencies:
  - python==3.11.7
  - numpy
  - pandas
  - scipy
  - matplotlib
  - pywavelets
  - setuptools<81
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu128
      - torch
      - torchvision
      - torchaudio
      - torch-dct
      - pytorch-wavelets