name: EVCA-gpu
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python==3.11.7
  - numpy
  - pandas
  - scipy
  - matplotlib
  - pywavelets
  - setuptools<81
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda
  - pip
  - pip:
      - pytorch-wavelets