import os
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt

def plot_frame_metrics_EVCA(args, csv_path):
    """
    Reads the CSV output generated by EVCA/VCA and plots the frame-level metrics.
    Dynamically scales the number of subplots based on the available metrics, 
    including the optional Colorfulness feature.
    """
    directory, file_name = os.path.split(args.csv)
    directory = './' if directory == '' else directory
    
    if not os.path.exists(csv_path):
        print(f"Error: CSV file {csv_path} not found. Cannot plot features.")
        return

    # Load the metrics
    df = pd.read_csv(csv_path)

    # Determine base metrics based on the selected method
    if args.method == 'VCA':
        metrics_to_plot = ['E', 'h', 'h2']
    elif args.method == 'EVCA':
        metrics_to_plot = ['SC', 'TC', 'TC2']
    else:
        metrics_to_plot = []

    # Dynamically include Colorfulness if it was calculated and saved to the CSV
    if 'Colorfulness' in df.columns:
        metrics_to_plot.append('Colorfulness')

    # Filter out any metrics that might be missing from the CSV to prevent KeyError
    valid_metrics = [m for m in metrics_to_plot if m in df.columns]
    
    if not valid_metrics:
        print("Error: No valid metrics found in the CSV to plot.")
        return

    num_metrics = len(valid_metrics)
    
    # Create a dynamic figure size based on the number of plots (3 vertical inches per plot)
    fig, axes = plt.subplots(num_metrics, 1, figsize=(10, 3 * num_metrics))
    
    # Handle the case where subplots() returns a single axis instead of a numpy array
    if num_metrics == 1:
        axes = [axes]
        
    for i, metric in enumerate(valid_metrics):
        # Give Colorfulness a distinct color (purple) compared to spatial/temporal (blue)
        line_color = 'purple' if metric == 'Colorfulness' else '#1f77b4'
        
        axes[i].plot(df[metric], label=metric, color=line_color, linewidth=1.5)
        axes[i].set_title(f'{metric} over Frames')
        axes[i].set_xlabel('Frame Index')
        axes[i].set_ylabel(metric)
        axes[i].grid(True, linestyle='--', alpha=0.7)
        axes[i].legend(loc='upper right')
        
        # Ensure the graph starts at frame 0 on the X-axis
        axes[i].set_xlim(left=0)

    # Automatically adjust subplot parameters to give specified padding
    plt.tight_layout()
    
    # Save the plot
    output_dir = './png/frame_metrics'
    os.makedirs(output_dir, exist_ok=True)

    video_name = Path(args.input).name[:-4]
    csv_base = file_name[:-4]
    plot_filename = f'{output_dir}/{csv_base}_{args.method}_{video_name}_frame_metrics.png'    
    
    plt.savefig(plot_filename, dpi=args.dpi)
    plt.close(fig)
    
    print(f"Feature plots successfully saved to: {plot_filename}")