import os
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt

def plot_frame_metrics_EVCA(args, csv_path):
    """
    Reads the CSV output generated by EVCA/VCA and plots the frame-level metrics.
    Dynamically scales the number of subplots based on the available metrics, 
    and groups TC and TC_MC onto the same plot for comparison.
    """
    directory, file_name = os.path.split(args.csv)
    directory = './' if directory == '' else directory
    
    if not os.path.exists(csv_path):
        print(f"Error: CSV file {csv_path} not found. Cannot plot features.")
        return

    # Load the metrics
    df = pd.read_csv(csv_path)
    
    # We will build a list of lists. Each sub-list represents one subplot axis.
    plot_groups = []
    
    base_tc_metric = None

    # Determine base metrics based on the selected method
    if args.method == 'VCA':
        for m in ['E', 'h', 'h2']:
            if m in df.columns: 
                plot_groups.append([m])
                if m == 'h':
                    base_tc_metric = 'h'
    elif args.method == 'EVCA':
        for m in ['SC', 'TC', 'TC2']:
            if m in df.columns: 
                plot_groups.append([m])
                if m == 'TC':
                    base_tc_metric = 'TC'

    # Add individual metrics
    for m in ['Colorfulness', 'SC_u', 'SC_v', 'MVC', 'TC_SAD']:
        if m in df.columns:
            plot_groups.append([m])
            
    # Group TC and TC_MC together on a single subplot axis
    tc_compare_group = []
    if 'TC_MC' in df.columns:
        if base_tc_metric:
            tc_compare_group.append(base_tc_metric)
        tc_compare_group.append('TC_MC')
        
    if tc_compare_group:
        plot_groups.append(tc_compare_group)
    
    if not plot_groups:
        print("Error: No valid metrics found in the CSV to plot.")
        return

    num_plots = len(plot_groups)
    
    # Create a dynamic figure size based on the number of plots (3 vertical inches per plot)
    fig, axes = plt.subplots(num_plots, 1, figsize=(10, 3 * num_plots))
    
    # Handle the case where subplots() returns a single axis instead of a numpy array
    if num_plots == 1:
        axes = [axes]
        
    # Dictionary mapping for line colors
    color_map = {
        'Colorfulness': 'purple',
        'SC_u': '#ff7f0e',   # Orange
        'SC_v': '#2ca02c',   # Green
        'MVC': '#d62728',    # Red
        'TC_SAD': '#8c564b', # Brown
        'TC_MC': '#e377c2'   # Pink
    }
        
    for i, group in enumerate(plot_groups):
        ax = axes[i]
        
        # Plot all metrics assigned to this specific subplot
        for metric in group:
            line_color = color_map.get(metric, '#1f77b4') # Default Blue
            ax.plot(df[metric], label=metric, color=line_color, linewidth=1.5)
            
        # Dynamically set title and y-label depending on if it's a single or grouped plot
        title = f"{' vs '.join(group)} Comparison" if len(group) > 1 else f"{group[0]} over Frames"
        y_label = "Value" if len(group) > 1 else group[0]
        
        ax.set_title(title)
        ax.set_xlabel('Frame Index')
        ax.set_ylabel(y_label)
        ax.grid(True, linestyle='--', alpha=0.7)
        ax.legend(loc='upper right')
        
        # Ensure the graph starts at frame 0 on the X-axis
        ax.set_xlim(left=0)

    # Automatically adjust subplot parameters to give specified padding
    plt.tight_layout()
    
    # Save the plot
    output_dir = './png/frame_metrics'
    os.makedirs(output_dir, exist_ok=True)

    video_name = Path(args.input).name[:-4]
    csv_base = file_name[:-4]
    plot_filename = f'{output_dir}/{csv_base}_{args.method}_{video_name}_frame_metrics.png'    
    
    plt.savefig(plot_filename, dpi=args.dpi)
    plt.close(fig)
    
    print(f"Feature plots successfully saved to: {plot_filename}")