"""Synthetic 8-bit yuv420 sequence generator with known ground-truth motion.

Each generator writes `<name>.yuv` (Y plane textured, U/V constant 128) plus a
`<name>.json` sidecar holding the exact motion parameters, so tests and the
validation harness can verify motion-estimation output against ground truth.

MV sign convention (matches SparsePatternBlockMatcher): the estimated MV (dy, dx)
of a block satisfies curr(y, x) ~= ref(y + dy, x + dx). For a sequence produced
by sliding a crop window over a fixed canvas with offset increment (vy, vx) per
frame, the expected MV is exactly (vy, vx).
"""
import argparse
import json
import math
from pathlib import Path

import numpy as np
from scipy.ndimage import gaussian_filter, map_coordinates


def make_base_texture(height: int, width: int, seed: int = 0) -> np.ndarray:
    """Band-pass filtered noise plus a few hard edges.

    The band-pass component gives SAD a unique minimum under translation, and the
    injected rectangles/lines add strong edges so DCT-based metrics are non-trivial.
    Returns a float32 array in [16, 235].
    """
    rng = np.random.default_rng(seed)
    noise = rng.standard_normal((height, width))
    bandpass = gaussian_filter(noise, sigma=1.5) - gaussian_filter(noise, sigma=6.0)
    bandpass /= np.abs(bandpass).max() + 1e-9
    img = 128.0 + 70.0 * bandpass

    # A few rectangles with hard edges
    for _ in range(8):
        h = int(rng.integers(height // 16, height // 4))
        w = int(rng.integers(width // 16, width // 4))
        y = int(rng.integers(0, height - h))
        x = int(rng.integers(0, width - w))
        img[y:y + h, x:x + w] += float(rng.choice([-45.0, 45.0]))

    # A couple of 3px-wide diagonal lines
    yy, xx = np.mgrid[0:height, 0:width]
    for _ in range(3):
        slope = float(rng.uniform(-1.5, 1.5))
        icpt = float(rng.uniform(0, height))
        mask = np.abs(yy - (slope * xx + icpt)) < 1.5
        img[mask] += float(rng.choice([-50.0, 50.0]))

    return np.clip(img, 16.0, 235.0).astype(np.float32)


def write_yuv420(path: Path, y_frames: list, gt: dict) -> None:
    """Writes 8-bit yuv420p with constant chroma and a ground-truth JSON sidecar."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    height, width = y_frames[0].shape
    uv = np.full((height // 2, width // 2), 128, dtype=np.uint8)
    with open(path, 'wb') as f:
        for y in y_frames:
            f.write(np.clip(np.rint(y), 0, 255).astype(np.uint8).tobytes())
            f.write(uv.tobytes())
            f.write(uv.tobytes())
    gt = dict(gt, width=width, height=height, frames=len(y_frames),
              pix_fmt='yuv420', bit_depth=8)
    with open(path.with_suffix('.json'), 'w') as f:
        json.dump(gt, f, indent=2)


def gen_translation(height: int, width: int, n_frames: int, vy: int, vx: int,
                    seed: int = 0) -> tuple:
    """Integer translation: crop window slides (vy, vx) px/frame over a fixed canvas."""
    span_y, span_x = abs(vy) * (n_frames - 1), abs(vx) * (n_frames - 1)
    canvas = make_base_texture(height + span_y + 8, width + span_x + 8, seed)
    oy0 = 4 + (span_y if vy < 0 else 0)
    ox0 = 4 + (span_x if vx < 0 else 0)
    frames = []
    for f in range(n_frames):
        oy, ox = oy0 + f * vy, ox0 + f * vx
        frames.append(canvas[oy:oy + height, ox:ox + width])
    gt = {'type': 'translation', 'mv_dy': vy, 'mv_dx': vx}
    return frames, gt


def gen_translation_halfpel(height: int, width: int, n_frames: int,
                            vy_hp: int, vx_hp: int, seed: int = 0) -> tuple:
    """Sub-pel translation: velocities given in half-pel units (vy_hp=1 -> 0.5 px/frame).

    Generated by sliding integer crops over a 2x-resolution canvas and 2x2
    box-downsampling, so the sub-pel shift is exact under bilinear models.
    """
    h2, w2 = height * 2, width * 2
    span_y, span_x = abs(vy_hp) * (n_frames - 1), abs(vx_hp) * (n_frames - 1)
    canvas = make_base_texture(h2 + span_y + 8, w2 + span_x + 8, seed)
    oy0 = 4 + (span_y if vy_hp < 0 else 0)
    ox0 = 4 + (span_x if vx_hp < 0 else 0)
    frames = []
    for f in range(n_frames):
        oy, ox = oy0 + f * vy_hp, ox0 + f * vx_hp
        crop = canvas[oy:oy + h2, ox:ox + w2]
        frames.append(crop.reshape(height, 2, width, 2).mean(axis=(1, 3)))
    gt = {'type': 'translation_halfpel', 'mv_dy': vy_hp / 2.0, 'mv_dx': vx_hp / 2.0}
    return frames, gt


def _sample_affine(canvas: np.ndarray, height: int, width: int,
                   scale: float, angle_deg: float) -> np.ndarray:
    """Samples an (height, width) frame from canvas center with zoom + rotation.

    Output pixel p maps to canvas coordinate c = R(angle) @ (p - center) / scale
    + canvas_center, i.e. scale > 1 zooms in.
    """
    cy, cx = (height - 1) / 2.0, (width - 1) / 2.0
    ccy, ccx = (canvas.shape[0] - 1) / 2.0, (canvas.shape[1] - 1) / 2.0
    yy, xx = np.mgrid[0:height, 0:width].astype(np.float64)
    yy -= cy
    xx -= cx
    a = math.radians(angle_deg)
    src_y = (math.cos(a) * yy - math.sin(a) * xx) / scale + ccy
    src_x = (math.sin(a) * yy + math.cos(a) * xx) / scale + ccx
    return map_coordinates(canvas, [src_y, src_x], order=1, mode='nearest').astype(np.float32)


def gen_zoom(height: int, width: int, n_frames: int, rate: float = 0.01,
             seed: int = 0) -> tuple:
    """Zoom about the frame center: scale factor 1 + rate*f at frame f (rate > 0 zooms in)."""
    canvas = make_base_texture(int(height * 1.5), int(width * 1.5), seed)
    frames = [_sample_affine(canvas, height, width, 1.0 + rate * f, 0.0)
              for f in range(n_frames)]
    gt = {'type': 'zoom', 'rate_per_frame': rate}
    return frames, gt


def gen_rotation(height: int, width: int, n_frames: int, deg_per_frame: float = 0.5,
                 seed: int = 0) -> tuple:
    """In-plane rotation about the frame center: angle deg_per_frame*f at frame f."""
    canvas = make_base_texture(int(height * 1.6), int(width * 1.6), seed)
    frames = [_sample_affine(canvas, height, width, 1.0, deg_per_frame * f)
              for f in range(n_frames)]
    gt = {'type': 'rotation', 'deg_per_frame': deg_per_frame}
    return frames, gt


def gen_static_noise(height: int, width: int, n_frames: int, sigma: float = 4.0,
                     seed: int = 0) -> tuple:
    """Static texture plus i.i.d. Gaussian noise per frame (zero true motion)."""
    base = make_base_texture(height, width, seed)
    rng = np.random.default_rng(seed + 1)
    frames = [np.clip(base + rng.standard_normal(base.shape).astype(np.float32) * sigma,
                      0, 255) for _ in range(n_frames)]
    gt = {'type': 'static_noise', 'sigma': sigma, 'mv_dy': 0, 'mv_dx': 0}
    return frames, gt


def gen_cut(height: int, width: int, n_frames: int, seed: int = 0) -> tuple:
    """Hard cut: static texture A, then an unrelated static texture B at n_frames//2."""
    a = make_base_texture(height, width, seed)
    b = make_base_texture(height, width, seed + 100)
    cut_at = n_frames // 2
    frames = [a] * cut_at + [b] * (n_frames - cut_at)
    gt = {'type': 'cut', 'cut_frame': cut_at}
    return frames, gt


# The standard suite generated by the CLI (name -> (generator, kwargs)).
STANDARD_SUITE = {
    'trans_p2': (gen_translation, {'vy': 0, 'vx': 2}),
    'trans_p5': (gen_translation, {'vy': 0, 'vx': 5}),
    'trans_p8': (gen_translation, {'vy': 0, 'vx': 8}),
    'trans_p16': (gen_translation, {'vy': 0, 'vx': 16}),
    'trans_p32': (gen_translation, {'vy': 0, 'vx': 32}),
    'trans_diag4': (gen_translation, {'vy': 4, 'vx': -4}),
    'trans_half': (gen_translation_halfpel, {'vy_hp': 0, 'vx_hp': 5}),
    'zoom': (gen_zoom, {'rate': 0.01}),
    'rotation': (gen_rotation, {'deg_per_frame': 0.5}),
    'static_noise': (gen_static_noise, {'sigma': 4.0}),
    'cut': (gen_cut, {}),
}


def generate_suite(out_dir: Path, width: int = 1920, height: int = 1080,
                   n_frames: int = 12, seed: int = 0) -> dict:
    """Generates the full standard suite; returns {name: yuv_path}."""
    out_dir = Path(out_dir)
    paths = {}
    for name, (gen, kwargs) in STANDARD_SUITE.items():
        frames, gt = gen(height, width, n_frames, seed=seed, **kwargs)
        path = out_dir / f'{name}_{width}x{height}.yuv'
        write_yuv420(path, frames, gt)
        paths[name] = path
    return paths


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Generate synthetic YUV test sequences.')
    parser.add_argument('--out-dir', type=str, default=str(Path(__file__).parent / 'synthetic_data'))
    parser.add_argument('--width', type=int, default=1920)
    parser.add_argument('--height', type=int, default=1080)
    parser.add_argument('--frames', type=int, default=12)
    parser.add_argument('--seed', type=int, default=0)
    args = parser.parse_args()
    paths = generate_suite(Path(args.out_dir), args.width, args.height, args.frames, args.seed)
    for name, p in paths.items():
        print(f'{name}: {p}')
